apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h7ec06ajm-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/h7ec06ajm-dotnet-basic-gitops